"""
FILE: patient_record.py
AUTHOR: 22326622
MODULE: COM5013 Algorithms & Data Structures

This module defines the **patientrecord** class, a small container for all
information about a patient in the triage system. Each record stores
immutable identifying fields such as the NHS number and date of birth, as
well as mutable clinical fields such as priority and blood type. In
addition to these properties, a patient record keeps its own log of events
in the form of a last-in, first-out (LIFO) stack. This history log
captures updates to the patient's status (for example, being sent to the
pharmacy or discharged) and allows the most recent entry to be viewed or
rolled back if necessary.

The :class:`patientrecord` class is used throughout the simulation:

* :mod:`Logic.patient_factory` constructs new records by passing in
  identifiers, names, and other attributes.
* :mod:`main` stores records in a hash map, places them in queues and
  buffers, and displays them via the command-line interface.
* :mod:`Logic.sorting_algorithms` relies on the fact that patient records can
  be compared using the ``<`` operator to order them by urgency.

Care has been taken to avoid circular imports: type hints for the history
stack are guarded with ``TYPE_CHECKING`` so that Python can see the names
without executing the import at runtime.
"""

from __future__ import annotations
from typing import TYPE_CHECKING

# Forward declaration to prevent Circular Import Error at runtime.
# This allows the Type Checker to see 'linkedstack' before the module is fully loaded.
if TYPE_CHECKING:
    from Structures.linked_structures import linkedstack

class patientrecord:
    """
    A simple container for patient information and status history.

    A ``patientrecord`` instance collects all of the details about one
    individual: their unique NHS number, date of birth, name, blood type
    and current priority (1 is most urgent). The NHS number and date of
    birth never change after the record is created; they are exposed as
    read-only properties so that code elsewhere cannot accidentally modify
    them. The ``priority`` field can be updated as a patient's condition
    changes, and each update is automatically recorded in the history log.

    The history log itself is a stack of messages describing events in
    reverse chronological order. This allows the most recent event to be
    inspected quickly via :meth:`get_current_status`. The log lives on
    the record and is not shared with any other object, which helps keep
    each patient's audit trail separate and encapsulated.
    """
    
    def __init__(self, nhs_number: str, dob: str, first_name: str, last_name: str, priority: int, blood_type: str):
        """
        Construct a new patient record with the supplied attributes.

        Parameters:
            nhs_number: a string that uniquely identifies this patient. In
                this simulation it is generated by the factory and used as
                the key in the hash map.
            dob: the patient's date of birth represented as a string in
                ``YYYY-MM-DD`` format. It is stored here for reference and
                never changes.
            first_name: the patient's given name.
            last_name: the patient's family name.
            priority: an integer between 1 and 5 indicating how urgent the
                patient's condition is. Smaller numbers mean higher
                urgency. Unlike the NHS number, this value can change
                during the simulation (for example, if a patient becomes
                more or less critical).
            blood_type: the patient's blood group (e.g. ``'A+'`` or ``'O-'``).

        When a record is created an internal history stack is also
        initialised and seeded with a message recording the starting
        priority. The stack is implemented using the :class:`Structures.linked_structures.linkedstack`
        class. Importing it here inside the constructor avoids a circular
        dependency at module load time.
        """
        # Local import to strictly adhere to dependency hierarchy.
        # Importing 'linkedstack' here avoids a global circular dependency loop 
        # with linked_structures.py, which imports 'node', which might infer 'patientrecord'.
        from Structures.linked_structures import linkedstack
        
        # Private attributes to enforce encapsulation
        self._nhs_number = nhs_number
        self._dob = dob
        self._first_name = first_name
        self._last_name = last_name
        self._priority = priority
        self._blood_type = blood_type
        
        # The LIFO Audit Log.
        # Justification: A Stack is used because the most recent clinical event 
        # is the most relevant for triage decisions.
        self.history_log: "linkedstack" = linkedstack()
        self.history_log.push(f"Patient record created with priority {priority}.")

    # --- Immutable Property Accessors (O(1)) ---
    # These prevent accidental modification of patient identity data.

        # @property ensures that the NHS number remains constant for the lifetime of the record.
        # Using the @property decorator transforms this method into a descriptor for controlled access,
        # removing the need for 'nhs_number = property(fget=_get_nhs_number)' in the class body.
        # This also means that during refactoring internal logic can change while the external interface stays stable.
    @property
    def nhs_number(self) -> str:
        """
        Return the patient's NHS number.

        The NHS number uniquely identifies each record in the system. This
        property is read=only; attempting to assign to it will result in an
        error. Accessing it simply returns the stored string.
        """
        return self._nhs_number

    @property
    def dob(self) -> str:
        """
        Return the patient's date of birth.

        The date of birth is stored as a simple string and cannot be
        modified after the record is created.
        """
        return self._dob

    @property
    def first_name(self) -> str:
        """
        Return the patient's given name.
        """
        return self._first_name

    @property
    def last_name(self) -> str:
        """
        Return the patient's family name.
        """
        return self._last_name

    @property
    def priority(self) -> int:
        """
        Return the patient's current priority level.

        Smaller numbers indicate higher urgency. This value may be
        changed during the simulation via the :meth:`priority` setter.
        """
        return self._priority

    @priority.setter
    def priority(self, new_priority: int):
        """
        Update the patient's priority and record the change.

        Parameters:
            new_priority: an integer between 1 and 5. Values outside this
                range are rejected with an error message. A smaller
                priority value means the patient is more urgent.

        Assigning a new priority automatically pushes a message onto the
        patient's history stack noting the change. This ensures there is an
        audit trail for all adjustments to a patient's triage level.
        """
        if not isinstance(new_priority, int) or not 1 <= new_priority <= 5:
            print(f"Error: Priority must be an integer between 1 and 5.")
            return
            
        self._priority = new_priority
        self.history_log.push(f"Priority updated to {new_priority}.")
        
    @property
    def blood_type(self) -> str:
        """
        Return the patient's blood group.

        This attribute is read-only and cannot be changed after the record
        is created.
        """
        return self._blood_type
        
    def get_current_status(self) -> str:
        """
        Look at the most recent event recorded for this patient.

        The patient's history log is stored as a stack; the most recent
        message sits on the top. This method peeks at the top of the
        stack without removing the entry. If there are no entries, a
        default string indicating the absence of status is returned.

        Returns:
            The most recent status message or ``"No status."`` if the log
            is empty.
        """
        status = self.history_log.peek()
        return status if status is not None else "No status."

    def update_status(self, status_message: str):
        """
        Add a new entry to the patient's history log.

        Parameters:
            status_message: a short description of something that has
                happened to the patient (for example, "Sent to Pharmacy").

        This method pushes the message onto the top of the internal
        history stack. The message will then appear as the current status
        until a new event occurs.
        """
        self.history_log.push(status_message)

    def __lt__(self, other):
        """
        Compare this record to another for sorting.

        This method implements the ``<`` operator so that lists of
        ``patientrecord`` objects can be sorted by the merge sort defined in
        :mod:`Logic.sorting_algorithms`. The comparison follows a two-step
        rule:

        1. **Priority:** a patient with a smaller priority number (higher
           urgency) is considered "less than" one with a larger number.
        2. **Tie-breaking:** if two patients have the same priority, the
           one with the smaller NHS number is considered "less than". This
           preserves the arrival order when sorting because NHS numbers are
           issued sequentially by the factory.

        Returns:
            ``True`` if this record should come before ``other`` in a sorted
            list, ``False`` otherwise.
        """
        if not isinstance(other, patientrecord):
            return NotImplemented
            
        # 1. Primary Key: Medical Priority (Lower P = Higher Urgency)
        if self._priority != other._priority:
            return self._priority < other._priority
            
        # 2. Secondary Key: NHS Number (Arrival Order)
        # FIX: Cast to int() so "10" is correctly treated as larger than "2".
        return int(self._nhs_number) < int(other._nhs_number)

    def __repr__(self) -> str:
        """
        Return a human-readable representation of the patient.

        This method returns a concise string showing the patient's NHS
        number, surname, first name, priority and blood type. It is used
        when printing lists of patients for debugging or display.
        """
        return f"[PatientRecord: {self._nhs_number} | {self._last_name}, {self._first_name} | P:{self._priority} | BT:{self._blood_type}]"